"""initial schema

Revision ID: dfcf5ad77d2e
Revises: None
Create Date: 2026-08-16 19:43:07.125768
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'dfcf5ad77d2e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clans',
    sa.Column('tag', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tag')
    )
    op.create_table('players',
    sa.Column('tag', sa.String(length=12), nullable=False),
    sa.Column('clan_tag', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clan_tag'], ['clans.tag'], ),
    sa.PrimaryKeyConstraint('tag')
    )
    op.create_table('wars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clan_tag', sa.String(length=12), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_fame', sa.Integer(), nullable=False),
    sa.Column('relaxed_days', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clan_tag'], ['clans.tag'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('war_id', sa.Integer(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('triggered_by', sa.String(length=20), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['war_id'], ['wars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_wars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('war_id', sa.Integer(), nullable=False),
    sa.Column('player_tag', sa.String(length=12), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('attacks_day1', sa.Integer(), nullable=False),
    sa.Column('attacks_day2', sa.Integer(), nullable=False),
    sa.Column('attacks_day3', sa.Integer(), nullable=False),
    sa.Column('attacks_day4', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('black_cards', sa.Integer(), nullable=False),
    sa.Column('incomplete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_tag'], ['players.tag'], ),
    sa.ForeignKeyConstraint(['war_id'], ['wars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('war_id', 'player_tag', name='uq_playerwar_war_player')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_wars')
    op.drop_table('evaluation_logs')
    op.drop_table('wars')
    op.drop_table('players')
    op.drop_table('clans')
    # ### end Alembic commands ###
